src/engine/botscript.ts, src/engine/context.ts, src/engine/index.ts, src/engine/machine.ts, src/engine/pattern.ts, src/engine/struct.ts, src/interfaces/activator.ts, test/e2e/todo.spec.ts, test/engine/botscript.spec.ts, test/engine/pattern.spec.ts
* Add trigger pattern capability
=> Dev pattern capability

README.md, examples/hello.bot
=> update document spec

README.md, package-lock.json, package.json, src/engine/botscript.ts, src/engine/context.ts, src/engine/machine.ts, src/engine/request.ts, src/engine/struct.ts, src/interfaces/types.ts, src/lib/utils.ts, test/engine/botscript.spec.ts, test/lib/utils.spec.ts, test/mocha.opts
=> Dev conditional dialogues

src/engine/botscript.ts, src/engine/request.ts, src/lib/utils.ts
Fix #6 
* Refactor emit command service with error-first style
=> Refactor bot engine

.github/workflows/ci.yml, package-lock.json, package.json, tsconfig.json
* Add github ci to publish npm pkg
=> Dev release pkg

.github/workflows/ci.yml, .npmrc, package.json
* Add ci workflows to deploy pkg to both registry NPM and GPR
=> Dev pkg registry

README.md, package-lock.json
Fix #8 fix #10 
* Update conditional dialogue
* Add spec plugins system
=> Update conditional dialogue

src/engine/botscript.ts, src/engine/context.ts, src/engine/machine.ts, src/engine/struct.ts, src/interfaces/types.ts, src/lib/utils.ts, src/plugins/addTimeNow.ts, src/plugins/index.ts, src/plugins/noReplyHandle.ts, src/plugins/normalize.ts, src/plugins/utils/clean.ts, src/plugins/wordnet.ts, test/engine/botscript.spec.ts
Fix #13
* add plugin system
* refactor conditional types
Checklists:
=> dev plugin system, refactor conditional types

README.md, src/engine/botscript.ts, src/engine/machine.ts, src/engine/request.ts, src/lib/utils.ts, test/engine/botscript.spec.ts
Fix #15 
* Refactor spec
* implement conditional activation
=> implement conditional activation

README.md
* Add npm badge
* Add link documentation to the wiki
* Refactor documentation section order
=> Refactor readme documentation

package.json, src/engine/machine.ts
* Fix conditional dialogue always fire if `currentDialogue` node is not clear
=> Fix conditional dialogue

package-lock.json, package.json, src/engine/botscript.ts
* Call plugin before bot engine starts
=> Fix plugin

package-lock.json, package.json, src/engine/botscript.ts, src/engine/context.ts, src/engine/machine.ts, src/engine/pattern.ts, src/engine/request.ts, test/engine/botscript.spec.ts, test/engine/pattern.spec.ts
* support activator access request context
* add request intent
=> Dev nlp pattern

README.md, examples/register.bot, package.json, src/engine/botscript.ts, src/engine/machine.ts, src/engine/pattern.ts, src/engine/struct.ts, src/lib/utils.ts, test/e2e/register-bot.spec.ts, test/engine/botscript.spec.ts, test/mocha.opts
=> Dev register bot

package-lock.json, package.json, src/engine/pattern.ts
* npm audit fix
* fix pattern captures result
=> Upgrade deps

src/engine/machine.ts
=> upgrade xstate eventless transition always

.gitignore, package-lock.json, package.json
=> Replace ts-node-dev

package-lock.json, package.json, src/engine/struct.ts, src/lib/utils.ts, test/command/http-method.spec.ts, test/directives/plugin.spec.ts, test/e2e/delay.spec.ts
=> Dev http method

package-lock.json, package.json, src/engine/context.ts, test/e2e/delay.spec.ts, test/engine/population.spec.ts
Support variable usage in format: $Titlecase
Example:
```bash
@ service1 put /api/http/put
+ put me
* true @> service1
- Result $message $Titlecase
```
=> support variable $Titlecase

package.json, src/engine/machine.ts
* Fix undefined references when request isFlowing but context does not contain flow (leads to unable to discover dialogue)
=> Fix guard is flow

README.md, examples/register.bot, package-lock.json, package.json, src/engine/botscript.ts, src/engine/context.ts, src/engine/machine.ts, src/engine/request.ts, src/engine/response.ts, src/lib/regex.ts, src/lib/utils.ts, test/dialogue/flow.spec.ts, test/e2e/register-bot.spec.ts, test/engine/botscript.spec.ts, test/engine/conditions.spec.ts, test/engine/plugin.spec.ts, test/plugin/plugin.spec.ts
Fix #48 
* Fix conditional reply (with new syntax)
* Add identifier to context, request
* Create new request from context
* Support multiple (AND) conditions for plugins
* Add scope context flows
=> Dev scope request

README.md, src/engine/botscript.ts, src/engine/context.ts, src/engine/machine.ts, src/engine/request.ts, src/engine/response.ts, src/lib/regex.ts, test/conditions/conditional-flow.spec.ts, test/dialogue/flow.spec.ts, test/engine/conditions.spec.ts
* $flows are violate, now it can be only access in current flows. So, if the flow ends, they are no longer exists!
* related to #48
=> Dev conditional flow

README.md
=> spec_definition: extend capacity

.mocharc.yml, README.md, package.json, src/engine/botscript.ts, test/directives/plugin.spec.ts
* new: plugin support post-processing
=> Dev plugin, support post-processing

src/engine/context.ts, src/interfaces/types.ts, src/lib/vm.ts, src/lib/vm2.ts, src/plugins/built-in.ts, test/lib/vm.spec.ts
* Fix plugin code support for browser
=> Wrap code for browser
